import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function LayoutLogin({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
